### ISSUE TITLE
Possible bug in UM/MOD

### ISSUE THREAD

**Issue by TG9541** [Picatout/stm8_eForth#3]
@MrMarkB found a bug in Dr. Ting's original STM8EF code that's likely also in your code base.

Please refer to https://github.com/TG9541/stm8ef/issues/400

**Comment by Picatout** [comment]
Bug corrected using [umMod.txt](https://github.com/TG9541/stm8ef/files/5926192/umMod.txt)
But this path had itself a bug that I corrected replading instruction **SRAW X** by **RRCW X** at **MMSMb** label.

**Comment by TG9541** [comment]
@Picatout thanks for figuring this and also https://github.com/TG9541/stm8ef/issues/401 out!

**Comment by Picatout** [comment]
applied applied correction for overflow control solve the issue when the upper part of dividend is == to divisor. udh must be smaller than divisor to avoid overflow.  I compared the result with gforth and they agree.

~$ gforth
Gforth 0.7.3, Copyright (C) 1995-2008 Free Software Foundation, Inc.
Gforth comes with ABSOLUTELY NO WARRANTY; for details type `license'
Type `bye' to exit
hex  ok
20000 8000 /mod . .  4 0  ok
20000 ffff /mod . .  2 2  ok
20000 8f00 /mod . .  3 5300  ok
20000 7f00 /mod . .  4 400  ok

**Comment by TG9541** [comment]
Thanks for the collaboration! 

I've referenced your repository in the Wiki [here](https://github.com/TG9541/stm8ef/wiki#about-stm8-eforth)
